[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = ["migrations", "alembic"]
fix = true

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "N",  # pep8-naming
  "UP", # pyupgrade
  "C90", # mccabe
  "B",  # bugbear
  "A",  # flake8-builtins
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]


[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = false
ignore_missing_imports = true
strict_optional = true
show_error_codes = true
exclude = ["alembic"]